import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Editor from "./components/Editor/editor";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Editor />
      </main>
    </>
  );
}
